cmd/snapd: make sure signal handlers are established during early daemon startup (#4934)
* cmd/snapd: make sure signal handlers are established during early daemon startup

Signal handlers for SIGTERM & SIGINT were only added once the daemon
initialization phase has completed. Given that the init phase does a fair amount
of work, SIGTERM or SIGINT received at this time would terminate the process,
without any chance for performing cleanup.

The problem would manifest itself as a failure in tests/main/snap-confine,
and one or more temporary files of snap-confine being left behind. This was
logged as:

   + aa-enforce /etc/apparmor.d/usr.lib.snapd.snap-confine.real

   ERROR: Conflicting profiles for /snap/core/4321/usr/lib/snapd/snap-confine defined in two files:
   - /etc/apparmor.d/snap.core.4321.usr.lib.snapd.snap-confine
   - /etc/apparmor.d/snap.core.4321.usr.lib.snapd.snap-confine.5GrtGCJBj87S