snap-confine: disable -Werror=array-bounds in __overflow tests
This should fix error on Ubuntu 22.10:
```
gcc -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wno-missing-field-initializers -Wno-unused-parameter -Werror  -I/usr/include/glib-2.0 -I/usr/lib/powerpc64le-linux-gnu/glib-2.0/include -D_ENABLE_FAULT_INJECTION -g -O3 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -MT libsnap-confine-private/libsnap_confine_private_unit_tests-string-utils-test.o -MD -MP -MF libsnap-confine-private/.deps/libsnap_confine_private_unit_tests-string-utils-test.Tpo -c -o libsnap-confine-private/libsnap_confine_private_unit_tests-string-utils-test.o `test -f 'libsnap-confine-private/string-utils-test.c' || echo './'`libsnap-confine-private/string-utils-test.c
In file included from libsnap-confine-private/string-utils-test.c:19:
In function ‘sc_string_append_char_pair’,
    inlined from ‘test_sc_string_append_char_pair__overflow’ at libsnap-confine-private/string-utils-test.c:395:3,
    inlined from ‘test_sc_string_append_char_pair__overflow’ at libsnap-confine-private/string-utils-test.c:391:13:
libsnap-confine-private/string-utils.c:169:26: error: array subscript [3, 9223372036854775807] is outside array bounds of ‘char[2]’ [-Werror=array-bounds]
  169 |         dst[dst_len + 0] = c1;
      |         ~~~~~~~~~~~~~~~~~^~~~
libsnap-confine-private/string-utils-test.c: In function ‘test_sc_string_append_char_pair__overflow’:
libsnap-confine-private/string-utils-test.c:394:22: note: at offset 3 into object ‘buf’ of size 2
  394 |                 char buf[2] = { 0 };
      |                      ^~~
In function ‘sc_string_append_char’,
    inlined from ‘test_sc_string_append_char__overflow’ at libsnap-confine-private/string-utils-test.c:307:3,
    inlined from ‘test_sc_string_append_char__overflow’ at libsnap-confine-private/string-utils-test.c:303:13:
libsnap-confine-private/string-utils.c:144:26: error: array subscript [2, 9223372036854775807] is outside array bounds of ‘char[1]’ [-Werror=array-bounds]
  144 |         dst[dst_len + 0] = c;
      |         ~~~~~~~~~~~~~~~~~^~~
libsnap-confine-private/string-utils-test.c: In function ‘test_sc_string_append_char__overflow’:
libsnap-confine-private/string-utils-test.c:306:22: note: at offset 2 into object ‘buf’ of size 1
  306 |                 char buf[1] = { 0 };
      |                      ^~~
```