Fix error on sudoers file
This change adds a new line in the /etc/sudoers file to prevent an error
which is happening in debian and fedora after latest updates:
    # syntax error, unexpected WORD, expecting END or ':' or '\n'

The error:

Error: 2020-09-28 21:54:59 Error executing
google:debian-sid-64:tests/main/sudo-env (sep282050-048295) :
-----
...
+ tests.session -u test exec sudo sh -c 'echo :$PATH:'
/etc/sudoers:28: syntax error, unexpected WORD, expecting END or ':' or
'\n'
test ALL=(ALL) NOPASSWD:ALL
^~~~

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: a terminal is required to read the password; either use the -S
option to read from standard input or configure an askpass helper