Disable test on uc20 due to network manager fails to start
Error:

+ network-manager.nmcli general

(process:13249): nmcli-CRITICAL **: Error: Could not create NMClient
object: The name :1.12 was not provided by any .service files.
+ sleep 1
+ for _ in $(seq 300)
+ network-manager.nmcli general
Error: NetworkManager is not running.