Fix for 1 test missing
Checking tests formatting
Checks failed for task
./tests/nested/manual/core20-boot-config-update/task.yaml
- Keys 'environment' and 'systems' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']

Crushing failure and despair.
Error: Process completed with exit code 1.