Fixing the tests layout
The list of errors:

Checking tests formatting
Checks failed for task ./tests/regression/lp-1813963/task.yaml
- Keys 'systems' and 'backends' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task ./tests/regression/lp-1597839/task.yaml
- Keys 'systems' and 'details' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task ./tests/lib/tools/suite/tests.session/task.yaml
- Keys 'execute' and 'restore' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task ./tests/main/config-versions/task.yaml
- Keys 'systems' and 'details' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task
./tests/main/classic-prepare-image-no-core/task.yaml
- Keys 'environment' and 'kill-timeout' do not follow the desired
order: ['summary', 'details', 'backends', 'systems', 'manual',
'priority', 'warn-timeout', 'kill-timeout', 'environment', 'prepare',
'restore', 'debug', 'execute']
Checks failed for task ./tests/main/classic-prepare-image/task.yaml
- Keys 'environment' and 'kill-timeout' do not follow the desired
order: ['summary', 'details', 'backends', 'systems', 'manual',
'priority', 'warn-timeout', 'kill-timeout', 'environment', 'prepare',
'restore', 'debug', 'execute']
Checks failed for task ./tests/main/lxd-postrm-purge/task.yaml
- Keys 'kill-timeout' and 'priority' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task ./tests/main/interfaces-fuse-support/task.yaml
- Keys 'systems' and 'details' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task ./tests/main/lxd/task.yaml
- Keys 'kill-timeout' and 'priority' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task ./tests/main/lxd-try/task.yaml
- Keys 'restore' and 'prepare' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task ./tests/main/classic-custom-device-reg/task.yaml
- Keys 'environment' and 'kill-timeout' do not follow the desired
order: ['summary', 'details', 'backends', 'systems', 'manual',
'priority', 'warn-timeout', 'kill-timeout', 'environment', 'prepare',
'restore', 'debug', 'execute']
Checks failed for task ./tests/main/interfaces-network-control/task.yaml
- Keys 'systems' and 'details' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task ./tests/main/interfaces-libvirt/task.yaml
- Keys 'systems' and 'details' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task
./tests/main/parallel-install-interfaces-content/task.yaml
- Keys 'backends' and 'details' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task ./tests/main/interfaces-gpg-keys/task.yaml
- Keys 'systems' and 'details' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
Checks failed for task
./tests/nested/manual/core20-custom-kernel-commandline/task.yaml
- Keys 'environment' and 'details' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']
- Keys 'debug' and 'prepare' do not follow the desired order:
['summary', 'details', 'backends', 'systems', 'manual', 'priority',
'warn-timeout', 'kill-timeout', 'environment', 'prepare', 'restore',
'debug', 'execute']

Crushing failure and despair.
Error: Process completed with exit code 1.