tests: ask tar to speak English
Whenever I run overlord tests on my box I get this error:

    ----------------------------------------------------------------------
    FAIL: <autogenerated>:1: snapshotSuite.TestSaveIntegrationFails

    using shellcheck: "/usr/bin/shellcheck"
    snapshotstate_test.go:681:
	c.Check(strings.Join(tasks[1].Log(), "\n"), check.Matches, `\S+ ERROR cannot create archive: .* Permission denied .and \d+ more.`)
    ... value string = "2020-02-18T18:31:30+01:00 ERROR cannot create archive: /bin/tar: common/common-too-snap: Nie można open: Brak dostępu (and 1 more)"
    ... regex string = "\\S+ ERROR cannot create archive: .* Permission denied .and \\d+ more."

    OOPS: 71 passed, 1 FAILED
    --- FAIL: TestSnapshot (1.15s)

As you may see, the error is caused by a localized output from tar(1).
This patch fixes this issue.

Signed-off-by: Zygmunt Krynicki <me@zygoon.pl>