Fix netplan test on i386 architecture
Skip i386 because core20 is not available for pc-i386 architecture

This is failing on beta validation:

+ snap install --dangerous netplan-snap-20.snap
error: cannot perform the following tasks:
- Ensure prerequisites for "netplan-snap" are available (cannot install
snap base "core20": no snap revision available as specified)