tests: tweak the libvirt interface test to work on 22.10
The test is failing with a non critical AppArmor error message, but the
real failure is due to QEMU command-line parsing:

    error: internal error: qemu unexpectedly closed the monitor:
    2022-10-03T11:56:15.932697Z qemu-system-x86_64:
    -device {"driver":"virtio-balloon-pci","id":"balloon0","bus":"pci.0","addr":"0x2"}:
    PCI: slot 2 function 0 not available for virtio-balloon-pci, in use by virtio-net-pci,id=(null)

This happens because something in libvirt (or maybe QEMU itself) adds an
implicit PCI device on address 0x2 -- the log line pasted above shows
what device is being added. This bug has also been noticed by other
projects, see comment 45 on https://bugzilla.redhat.com/show_bug.cgi?id=2034160

The workaround we use is to specify a virtio-net-pci device on another
PCI address, in order to avoid the address conflict.