Fix snap-validate-enforce in opensuse-tumbleweed
This change is to fix in opensuse tumbleweed the error:

+ snap install hello-world
+ MATCH 'error: cannot install "hello-world": cannot install snap
"hello-world" due to'
grep error: pattern not found, got:
error: cannot install "hello-world": cannot install snap
       "hello-world" due to enforcing rules of validation set
       16/xSfWKGdLoQBoQx88vIM1MpbFNMq53t1f/testenforce1/1